ADULT = "ADULT"
SENIOR = "SENIOR_CITIZEN"
KID = "KID"

PASSENGER_TYPES = (ADULT, SENIOR, KID)

CENTRAL = "CENTRAL"
AIRPORT = "AIRPORT"
STATIONS = (CENTRAL, AIRPORT)

FORWARD = "FORWARD"
RETURN = "RETURN"

SERVICE_CHARGE_RATE = 0.02
DISCOUNT_RATE = 0.5
